apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"jira-worker"},"name":"jira-worker","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jira-worker"}},"template":{"metadata":{"labels":{"app":"jira-worker"}},"spec":{"containers":[{"command":["php","artisan","queue:work","redis","--queue=jira-imports","--sleep=3","--tries=1","--timeout=1200"],"image":"deampuleadd/premium-app:k8s","imagePullPolicy":"Always","name":"worker","volumeMounts":[{"mountPath":"/var/www/html/.env","name":"env-secret-volume","subPath":".env"},{"mountPath":"/var/www/html/public/images","name":"nfs-storage","subPath":"images"}]}],"volumes":[{"name":"env-secret-volume","secret":{"secretName":"sealed-env-secret"}},{"name":"nfs-storage","persistentVolumeClaim":{"claimName":"nfs-main-pvc"}}]}}}}
  creationTimestamp: "2025-10-25T07:55:07Z"
  generation: 1
  labels:
    app: jira-worker
  name: jira-worker
  namespace: default
  resourceVersion: "1963882"
  uid: dae1d639-db1a-4c63-b170-a055a20aa88b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jira-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jira-worker
    spec:
      containers:
      - command:
        - php
        - artisan
        - queue:work
        - redis
        - --queue=jira-imports
        - --sleep=3
        - --tries=1
        - --timeout=1200
        image: deampuleadd/premium-app:k8s
        imagePullPolicy: Always
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/.env
          name: env-secret-volume
          subPath: .env
        - mountPath: /var/www/html/public/images
          name: nfs-storage
          subPath: images
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: env-secret-volume
        secret:
          defaultMode: 420
          secretName: sealed-env-secret
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-main-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-25T07:55:11Z"
    lastUpdateTime: "2025-10-25T07:55:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-25T07:55:07Z"
    lastUpdateTime: "2025-10-25T07:55:11Z"
    message: ReplicaSet "jira-worker-64c4f8fff8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1