apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"premium-app","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"premium-app"}},"template":{"metadata":{"labels":{"app":"premium-app"}},"spec":{"containers":[{"image":"deampuleadd/premium-app:k8s","name":"php-fpm","volumeMounts":[{"mountPath":"/var/www/html/.env","name":"env-secret-volume","subPath":".env"},{"mountPath":"/var/www/html/public/images","name":"nfs-storage","subPath":"images"}]},{"image":"deampuleadd/custom-nginx:k8s","name":"nginx","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/var/www/html/public/images","name":"nfs-storage","subPath":"images"}]}],"volumes":[{"name":"env-secret-volume","secret":{"secretName":"sealed-env-secret"}},{"name":"nfs-storage","persistentVolumeClaim":{"claimName":"nfs-main-pvc"}}]}}}}
  creationTimestamp: "2025-10-25T07:37:36Z"
  generation: 1
  name: premium-app
  namespace: default
  resourceVersion: "1962656"
  uid: a09c7387-569b-4f20-aad7-3651c1cc510d
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: premium-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: premium-app
    spec:
      containers:
      - image: deampuleadd/premium-app:k8s
        imagePullPolicy: IfNotPresent
        name: php-fpm
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/.env
          name: env-secret-volume
          subPath: .env
        - mountPath: /var/www/html/public/images
          name: nfs-storage
          subPath: images
      - image: deampuleadd/custom-nginx:k8s
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/public/images
          name: nfs-storage
          subPath: images
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: env-secret-volume
        secret:
          defaultMode: 420
          secretName: sealed-env-secret
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-main-pvc
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-10-25T07:41:36Z"
    lastUpdateTime: "2025-10-25T07:41:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-25T07:37:36Z"
    lastUpdateTime: "2025-10-25T07:41:36Z"
    message: ReplicaSet "premium-app-6dc6b6b8b5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2