apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"reverb","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"reverb"}},"template":{"metadata":{"labels":{"app":"reverb"}},"spec":{"containers":[{"command":["php","artisan","reverb:start","--host=0.0.0.0"],"image":"deampuleadd/premium-app:k8s","imagePullPolicy":"Always","name":"reverb","ports":[{"containerPort":6001}],"volumeMounts":[{"mountPath":"/var/www/html/.env","name":"env-secret-volume","subPath":".env"}]}],"volumes":[{"name":"env-secret-volume","secret":{"secretName":"sealed-env-secret"}}]}}}}
  creationTimestamp: "2025-10-25T07:41:01Z"
  generation: 1
  name: reverb
  namespace: default
  resourceVersion: "1962549"
  uid: e6eee75f-c372-4ac5-a7a9-ab35ac044388
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: reverb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reverb
    spec:
      containers:
      - command:
        - php
        - artisan
        - reverb:start
        - --host=0.0.0.0
        image: deampuleadd/premium-app:k8s
        imagePullPolicy: Always
        name: reverb
        ports:
        - containerPort: 6001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/.env
          name: env-secret-volume
          subPath: .env
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: env-secret-volume
        secret:
          defaultMode: 420
          secretName: sealed-env-secret
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-25T07:41:03Z"
    lastUpdateTime: "2025-10-25T07:41:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-25T07:41:01Z"
    lastUpdateTime: "2025-10-25T07:41:03Z"
    message: ReplicaSet "reverb-5c47d96bd6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1