apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"n8n-service","namespace":"default"},"spec":{"ports":[{"port":5678,"protocol":"TCP","targetPort":5678}],"selector":{"app":"n8n"}}}
  creationTimestamp: "2025-10-25T08:08:55Z"
  name: n8n-service
  namespace: default
  resourceVersion: "1965201"
  uid: d42ce07a-3758-4b3c-82ec-ff463a3b89e1
spec:
  clusterIP: 10.106.90.73
  clusterIPs:
  - 10.106.90.73
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: n8n
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}