apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"reverb","namespace":"default"},"spec":{"ports":[{"port":6001,"protocol":"TCP","targetPort":6001}],"selector":{"app":"reverb"}}}
  creationTimestamp: "2025-10-25T07:41:01Z"
  name: reverb
  namespace: default
  resourceVersion: "1962522"
  uid: 9de9893d-b16a-412b-9c78-da22370e6857
spec:
  clusterIP: 10.105.172.65
  clusterIPs:
  - 10.105.172.65
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6001
    protocol: TCP
    targetPort: 6001
  selector:
    app: reverb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}