apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: default
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        command: ["redis-server", "/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: nfs-storage
          mountPath: /data
          subPath: redis
        - name: config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf

      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-main-pvc
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis.conf
            path: redis.conf